version: 2

seeds:
  - name: raw_customers
    description: one unique customer per row
    columns:
      - name: id
        decription: primary key
        data_tests:
          - unique
          - not_null

  - name: raw_orders
    description: one order per row
    columns:
      - name: id
        description: primary key
        data_tests:
          - unique
          - not_null
      - name: status
        description: "{{ doc('order_status') }}"
        data_tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending','returned']
      - name: user_id
        data_tests:
          - relationships:
              to: ref('raw_customers')
              field: id

  - name: raw_payments
    description: one payment per row
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: payment_method
        data_tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']
